// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIIh4gmgGGYACLe08Mb_0NYJnUA2OOlNM',
    appId: '1:306191065298:web:75a509dfdb900bb2d40d0b',
    messagingSenderId: '306191065298',
    projectId: 'studybuddy-81835',
    authDomain: 'studybuddy-81835.firebaseapp.com',
    storageBucket: 'studybuddy-81835.firebasestorage.app',
    measurementId: 'G-VQ1JQSHC3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuIzUK_b3fWojv29nTFLBa3gX4vLA8ZJU',
    appId: '1:306191065298:android:36756295b7a83bd0d40d0b',
    messagingSenderId: '306191065298',
    projectId: 'studybuddy-81835',
    storageBucket: 'studybuddy-81835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzBQCGe42ke3XsyLrWLKJN7MZwnbF9JlQ',
    appId: '1:306191065298:ios:98733bf7096473f5d40d0b',
    messagingSenderId: '306191065298',
    projectId: 'studybuddy-81835',
    storageBucket: 'studybuddy-81835.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzBQCGe42ke3XsyLrWLKJN7MZwnbF9JlQ',
    appId: '1:306191065298:ios:98733bf7096473f5d40d0b',
    messagingSenderId: '306191065298',
    projectId: 'studybuddy-81835',
    storageBucket: 'studybuddy-81835.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIIh4gmgGGYACLe08Mb_0NYJnUA2OOlNM',
    appId: '1:306191065298:web:b0421287c6a30e3bd40d0b',
    messagingSenderId: '306191065298',
    projectId: 'studybuddy-81835',
    authDomain: 'studybuddy-81835.firebaseapp.com',
    storageBucket: 'studybuddy-81835.firebasestorage.app',
    measurementId: 'G-VJC2CHEJHH',
  );

}